version: '3.1'

# Services
services:
  # nginx Service
  nginx_service:
    container_name: nginx_container
    image: nginx_image
    restart: always
    build: .
    ports:
      - "1111:80" 
    networks:
      - nginx_network  
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./html:/usr/share/nginx/html

# Networks
networks:
  nginx_network:
    name: nginx_network
    driver: bridge
